### ISSUE TITLE
Corrección en listado Clientes

### ISSUE THREAD

**Issue by leonardomv** [MattSeltz/drakkarGroupApp#2]
- [x] El texto "Buscador" tiene que ser reemplazado por un input para buscar los clientes.
- [x] El listado se actualiza al ingresar 3 caracteres. Se muestran las coincidencias directamente en el listado de clientes, sin mostrar ninfuna otra información.

![image](https://github.com/MattSeltz/drakkarGroupApp/assets/13360709/10b52318-96fd-4872-8a70-2863ff670ff0)

**Comment by leonardomv** [comment]
Genial el Filtrado

**Comment by MattSeltz** [comment]
Que bueno que funcionó !

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
